sudo: false

language: go
go:
  - 1.4
  - 1.5

before_install:
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/mattn/goveralls
  - go get github.com/mitchellh/gox

install:
  - make updatedeps

script:
  - gox -osarch="linux/amd64" -output=diemon github.com/yieldbot/diemon/src
