sudo: false

language: go
go:
  - 1.4
  - 1.5.1
  - 1.5.2

before_install:
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/mattn/goveralls
  - go get github.com/mitchellh/gox

script:
  - make pkgbase=github.com/yieldbot pkg=handler-elasticsearch-status format
  - make pkgbase=github.com/yieldbot pkg=handler-elasticsearch-status lint
  - make pkgbase=github.com/yieldbot pkg=handler-elasticsearch-status vet
  - make pkgbase=github.com/yieldbot pkg=handler-elasticsearch-status build
